In [56]:
#Installation des packages
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [57]:
#Telechargement du dataset
df=load_breast_cancer()

In [58]:
X=df.data
y=df.target

In [59]:
print(df.DESCR)



.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [60]:
print(X)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [61]:
#Normalisation
X=StandardScaler().fit_transform(X)
print(X)

[[ 1.09706398 -2.07333501  1.26993369 ...  2.29607613  2.75062224
   1.93701461]
 [ 1.82982061 -0.35363241  1.68595471 ...  1.0870843  -0.24388967
   0.28118999]
 [ 1.57988811  0.45618695  1.56650313 ...  1.95500035  1.152255
   0.20139121]
 ...
 [ 0.70228425  2.0455738   0.67267578 ...  0.41406869 -1.10454895
  -0.31840916]
 [ 1.83834103  2.33645719  1.98252415 ...  2.28998549  1.91908301
   2.21963528]
 [-1.80840125  1.22179204 -1.81438851 ... -1.74506282 -0.04813821
  -0.75120669]]


In [62]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)
print(X_train.shape,X_test.shape)

(455, 30) (114, 30)


Creation du reseau de neurone

In [63]:
import tensorflow as tf

In [64]:

model=tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(units=15,activation="relu",kernel_initializer="uniform",input_dim=30))
model.add(tf.keras.layers.Dense(units=1,activation="sigmoid",kernel_initializer="uniform"))
 

In [65]:
model.compile(optimizer='adam',loss="binary_crossentropy",metrics=['binary_accuracy'])

In [66]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 15)                465       
                                                                 
 dense_7 (Dense)             (None, 1)                 16        
                                                                 
Total params: 481 (1.88 KB)
Trainable params: 481 (1.88 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [67]:
model.fit(X_train,y_train,batch_size=10,epochs=100)

Epoch 1/100


46/46 [==============================] - 1s 2ms/step - loss: 0.6517 - binary_accuracy: 0.8571
Epoch 2/100
46/46 [==============================] - 0s 2ms/step - loss: 0.4551 - binary_accuracy: 0.9385
Epoch 3/100
46/46 [==============================] - 0s 2ms/step - loss: 0.2619 - binary_accuracy: 0.9516
Epoch 4/100
46/46 [==============================] - 0s 2ms/step - loss: 0.1766 - binary_accuracy: 0.9692
Epoch 5/100
46/46 [==============================] - 0s 2ms/step - loss: 0.1379 - binary_accuracy: 0.9714
Epoch 6/100
46/46 [==============================] - 0s 2ms/step - loss: 0.1167 - binary_accuracy: 0.9736
Epoch 7/100
46/46 [==============================] - 0s 2ms/step - loss: 0.1027 - binary_accuracy: 0.9758
Epoch 8/100
46/46 [==============================] - 0s 2ms/step - loss: 0.0925 - binary_accuracy: 0.9780
Epoch 9/100
46/46 [==============================] - 0s 2ms/step - loss: 0.0853 - binary_accuracy: 0.9824
Epoch 10/100
46/46 [==============================] - 0s 2

In [68]:
test_loss,acc_loss=model.evaluate(X_test,y_test)

4/4 [==============================] - 0s 2ms/step - loss: 0.1245 - binary_accuracy: 0.9649


In [72]:
X_test[2].shape

(30,)